# Generated by Django 5.2.8 on 2025-11-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
